/*
 * TreeRePair is an implementation of the Re-pair for Trees algorithm.
 *
 * Copyright (C) 2010  Roy Mennicke
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License Version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License Version 3 for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not,
 * see <http://www.gnu.org/licenses/gpl-3.0.txt>.
 */
#pragma once

#include "TreeRePairMacros.h"

#include <stack>

class SymbolReplacer;

/**
 * This class implements the decompressor for the files generated by
 * the TreeRePair algorithm, i.e., it decompresses the succinct coding
 * to retrieve the contained linear SLCF tree grammar G and after that
 * it computes val(G) (i.e. the tree which is represented by G is
 * obtained).
 */
class TreeDePairAlgorithm
{
public:
	/**
	 * The constructor of the decompressor.
	 * @param pFilePath Specifies the output file of TreeRePair which
	 *  shall be decompressed.
	 */
	TreeDePairAlgorithm(char * pFilePath);

	~TreeDePairAlgorithm(void);
};
